version: '3'
services:
  main-server:
    depends_on:
      - db-server
      - redis-server
    restart: always
    build:
      context: server
      dockerfile: ./Dockerfile
#    entrypoint: "npm run start:dev"
    volumes:
      - ./server:/usr/src/app
    ports:
      - '3001:3001'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOSTNAME: "db-server"
      DB_PORT: "27017"
      REDIS_HOSTNAME: "redis-server"
      REDIS_PORT: "6379"
      VERIFY_EMAIL_LIMIT: "10"
  db-server:
    restart: always
    image: mongo:6.0.14
    ports:
      - '27017:27017'
    volumes:
      - 'mongodbdata:/data/db'
  frontend-server:
    restart: always
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis-server:
    restart: always
    image: redis:7.2.4
    ports:
      - '6379:6379'

volumes:
  mongodbdata: